### ISSUE TITLE
testing practice ( code review)

### ISSUE THREAD

**Issue by tylher** [Yazino12/testing-practice#1]
@Yazino12 Good job so far 👍 , but there are a few issues you may need to change

- Babel could be installed so that you may be able to use the es6 export and import syntax
- What do you think about creating a new file for the calculator and exporting it as a class in the test file so your code can look neat?

cheers and happy coding 👍

**Comment by Yazino12** [comment]
Hello @tylher, Thanks for pointing these issues out, I'll implement them as soon as possible 📝.
